# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Client_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Client(object):
    def setupUi(self, Client):
        xSize = 1920
        ySize = 1080

        Client.setObjectName("Client")
        Client.resize(xSize, ySize)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Client.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        Client.setFont(font)
        Client.setStyleSheet("QWidget{\n"
"background:#484848;\n"
"}\n"
"QAbstractButton{\n"
"border-style:none;\n"
"border-radius:0px;\n"
"padding:5px;\n"
"color:#DCDCDC;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"QAbstractButton:hover{\n"
"color:#FFFFFF;\n"
"background-color:#00BB9E;\n"
"}\n"
"QAbstractButton:pressed{\n"
"color:#DCDCDC;\n"
"border-style:solid;\n"
"border-width:0px 0px 0px 2px;\n"
"padding:4px 4px 4px 2px;\n"
"border-color:#00BB9E;\n"
"background-color:#444444;\n"
"}\n"
"QLabel{\n"
"color:#DCDCDC;\n"
"border:1px solid #242424;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"QLabel:focus{\n"
"border:1px solid #00BB9E;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #646464,stop:1 #525252);\n"
"}\n"
"QLineEdit{\n"
"border:1px solid #242424;\n"
"border-radius:3px;\n"
"padding:2px;\n"
"background:none;\n"
"selection-background-color:#484848;\n"
"selection-color:#DCDCDC;\n"
"}\n"
"QLineEdit:focus,QLineEdit:hover{\n"
"border:1px solid #242424;\n"
"}\n"
"QLineEdit{\n"
"border:1px solid #242424;\n"
"border-radius:3px;\n"
"padding:2px;\n"
"background:none;\n"
"selection-background-color:#484848;\n"
"selection-color:#DCDCDC;\n"
"}\n"
"\n"
"QLineEdit:focus,QLineEdit:hover{\n"
"border:1px solid #242424;\n"
"}\n"
"QLineEdit{\n"
"lineedit-password-character:9679;\n"
"}\n"
"QSlider::groove:horizontal,QSlider::add-page:horizontal{\n"
"height:3px;\n"
"border-radius:3px;\n"
"background:#18181a;\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal{\n"
"height:8px;\n"
"border-radius:3px;\n"
"background:#008aff;\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal{\n"
"width:12px;\n"
"margin-top:-5px;\n"
"margin-bottom:-4px;\n"
"border-radius:6px;\n"
"background:qradialgradient(spread:pad,cx:0.5,cy:0.5,radius:0.5,fx:0.5,fy:0.5,stop:0.6 #565656,stop:0.8 #565656);\n"
"}\n"
"\n"
"\n"
"QSlider::groove:vertical,QSlider::sub-page:vertical{\n"
"width:3px;\n"
"border-radius:3px;\n"
"background:#18181a;\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:vertical{\n"
"width:8px;\n"
"border-radius:3px;\n"
"background:#008aff;\n"
"}\n"
"\n"
"\n"
"QSlider::handle:vertical{\n"
"height:12px;\n"
"margin-left:-5px;\n"
"margin-right:-4px;\n"
"border-radius:6px;\n"
"background:qradialgradient(spread:pad,cx:0.5,cy:0.5,radius:0.5,fx:0.5,fy:0.5,stop:0.6 #565656,stop:0.8 #565656);\n"
"}\n"
"")
        #Video Screen
        self.label_Video = QtWidgets.QLabel(Client)
        self.label_Video.setGeometry(QtCore.QRect(1, 42, xSize - 400, ySize - 50))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.label_Video.setFont(font)
        self.label_Video.setText("")
        self.label_Video.setObjectName("label_Video")

        #Forward Button
        self.Btn_ForWard = QtWidgets.QPushButton(Client)
        self.Btn_ForWard.setGeometry(QtCore.QRect(xSize - 250, 460, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.Btn_ForWard.setFont(font)
        self.Btn_ForWard.setStyleSheet("")
        self.Btn_ForWard.setObjectName("Btn_ForWard")
        
        # Top Bar
        self.name = QtWidgets.QLabel(Client)
        self.name.setGeometry(QtCore.QRect(0, 1, xSize - 100, 40))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.name.setFont(font)
        self.name.setStyleSheet("")
        self.name.setObjectName("name")

        #Left Button
        self.Btn_Turn_Left = QtWidgets.QPushButton(Client)
        self.Btn_Turn_Left.setGeometry(QtCore.QRect(xSize - 350, 510, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.Btn_Turn_Left.setFont(font)
        self.Btn_Turn_Left.setStyleSheet("")
        self.Btn_Turn_Left.setObjectName("Btn_Turn_Left")

        #Back Button
        self.Btn_BackWard = QtWidgets.QPushButton(Client)
        self.Btn_BackWard.setGeometry(QtCore.QRect(xSize - 250, 560, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.Btn_BackWard.setFont(font)
        self.Btn_BackWard.setStyleSheet("")
        self.Btn_BackWard.setObjectName("Btn_BackWard")

        #Right Button
        self.Btn_Turn_Right = QtWidgets.QPushButton(Client)
        self.Btn_Turn_Right.setGeometry(QtCore.QRect(xSize - 150, 510, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.Btn_Turn_Right.setFont(font)
        self.Btn_Turn_Right.setStyleSheet("")
        self.Btn_Turn_Right.setObjectName("Btn_Turn_Right")

        #Video Button
        self.Btn_Video = QtWidgets.QPushButton(Client)
        self.Btn_Video.setGeometry(QtCore.QRect(xSize - 150, 380, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.Btn_Video.setFont(font)
        self.Btn_Video.setStyleSheet("")
        self.Btn_Video.setObjectName("Btn_Video")

        #Close Button
        self.Window_Close = QtWidgets.QPushButton(Client)
        self.Window_Close.setGeometry(QtCore.QRect(xSize - 50, 1, 50, 40))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.Window_Close.setFont(font)
        self.Window_Close.setObjectName("Window_Close")

        #IP Address
        self.IP = QtWidgets.QLineEdit(Client)
        self.IP.setGeometry(QtCore.QRect(xSize - 350, 380, 101, 30))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.IP.setFont(font)
        self.IP.setStyleSheet("")
        self.IP.setObjectName("IP")

        #Connect Button
        self.Btn_Connect = QtWidgets.QPushButton(Client)
        self.Btn_Connect.setGeometry(QtCore.QRect(xSize - 250, 380, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.Btn_Connect.setFont(font)
        self.Btn_Connect.setObjectName("Btn_Connect")

        #Minimize Window Button
        self.Window_Min = QtWidgets.QPushButton(Client)
        self.Window_Min.setGeometry(QtCore.QRect(xSize - 100, 1, 50, 40))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.Window_Min.setFont(font)
        self.Window_Min.setObjectName("Window_Min")

        self.Btn_Mode1 = QtWidgets.QRadioButton(Client)
        self.Btn_Mode1.setGeometry(QtCore.QRect(xSize - 150, 410, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.Btn_Mode1.setFont(font)
        self.Btn_Mode1.setObjectName("Btn_Mode1")
        
        self.retranslateUi(Client)
        QtCore.QMetaObject.connectSlotsByName(Client)

    def retranslateUi(self, Client):
        _translate = QtCore.QCoreApplication.translate
        Client.setWindowTitle(_translate("Client", "freenove"))
        self.Btn_ForWard.setText(_translate("Client", "ForWard"))
        self.Btn_Turn_Left.setText(_translate("Client", "Turn Left"))
        self.Btn_BackWard.setText(_translate("Client", "BackWard"))
        self.Btn_Turn_Right.setText(_translate("Client", "Turn Right"))
        self.Btn_Video.setText(_translate("Client", "Open Video"))
        self.Window_Close.setText(_translate("Client", "×"))
        self.IP.setText(_translate("Client", "192.168.1.4"))
        self.Btn_Connect.setText(_translate("Client", "Connect"))
        self.Window_Min.setText(_translate("Client", "-"))
        self.Btn_Mode1.setText(_translate("Client", "M-Free"))
